package threshsig;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.IOException;
import java.math.BigInteger;

/**
 * Group key for (k,l) threshold scheme. Generated by Dealer.
 * Can be serialized for wire/key file and reconstructed from public params for verification.
 */
public class GroupKey {
  private final int k, l;
  private final BigInteger e, n;

  public GroupKey(final int k, final int l, final int keysize, final BigInteger v,
      final BigInteger e, final BigInteger n) {
    this.k = k;
    this.l = l;
    this.e = e;
    this.n = n;
  }

  /** Reconstruct from public params only (for verification when receiving QC). */
  public static GroupKey fromPublicParams(int k, int l, BigInteger n, BigInteger e) {
    return new GroupKey(k, l, 0, BigInteger.ZERO, e, n);
  }

  public int getK() { return k; }
  public int getL() { return l; }
  public BigInteger getModulus() { return n; }
  public BigInteger getExponent() { return e; }

  /** Serialize for wire or key file. */
  public byte[] toBytes() throws IOException {
    ByteArrayOutputStream out = new ByteArrayOutputStream();
    DataOutputStream d = new DataOutputStream(out);
    d.writeInt(k);
    d.writeInt(l);
    byte[] nBytes = n.toByteArray();
    d.writeInt(nBytes.length);
    d.write(nBytes);
    byte[] eBytes = e.toByteArray();
    d.writeInt(eBytes.length);
    d.write(eBytes);
    d.flush();
    return out.toByteArray();
  }

  /** Deserialize from bytes. */
  public static GroupKey fromBytes(byte[] b) throws IOException {
    DataInputStream in = new DataInputStream(new ByteArrayInputStream(b));
    int k = in.readInt();
    int l = in.readInt();
    int nLen = in.readInt();
    byte[] nBytes = new byte[nLen];
    in.readFully(nBytes);
    int eLen = in.readInt();
    byte[] eBytes = new byte[eLen];
    in.readFully(eBytes);
    return fromPublicParams(k, l, new BigInteger(nBytes), new BigInteger(eBytes));
  }
}
